name: db_vendor
description: A new Flutter project.
publish_to: "none"
version: 1.0.146+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.1.0
  animations: ^2.0.1
  another_flushbar: ^1.10.24
  awesome_notifications: ^0.0.6+10
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.1.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  flare_splash_screen: ^4.0.0
  flutter_cache: ^0.1.0
  flutter_snake_navigationbar: ^0.5.0
  flutter_staggered_grid_view: ^0.3.4
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.1.0
  get: ^4.3.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  google_place: ^0.4.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  introduction_screen: ^2.0.0
  location: ^4.3.0
  numberpicker: ^2.1.1
  pedantic: ^1.11.0
  permission_handler: ^8.1.4+2
  pin_code_fields: ^7.3.0
  smooth_star_rating: ^1.1.1
  sms_autofill: ^2.0.1
  url_launcher: ^6.0.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  hive_generator: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/images/
    - assets/
    - assets/icons/
    - assets/docs/
