name: db_vendor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  animations: ^2.0.1
  another_flushbar: ^1.10.24
  awesome_notifications: ^0.0.6+10
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.0
  cupertino_icons: ^1.0.3
  firebase: ^9.0.1
  firebase_analytics: ^8.3.0
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_crashlytics: ^2.0.4
  firebase_messaging: ^10.0.5
  flare_splash_screen: ^4.0.0
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.0.1
  flutter_cache: ^0.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_restart: ^0.0.3
  flutter_snake_navigationbar: ^0.5.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  google_place: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  html: ^0.15.0
  image: ^3.0.2
  intl: ^0.17.0
  introduction_screen: ^2.0.0
  location: ^4.3.0
  numberpicker: ^1.0.0
  pedantic: ^1.11.0
  permission_handler: ^8.1.4+2
  pin_code_fields: ^7.3.0
  rubber: ^0.5.0
  smooth_star_rating: ^1.1.1
  sms_autofill: ^2.0.1
  syncfusion_flutter_pdfviewer: ^19.2.56-beta
  url_launcher: ^6.0.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
    - assets/
    - assets/icons/
    - assets/docs/
